name: edge-caddy

services:
  caddy:
    image: caddy:2-alpine
    container_name: edge-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - BASIC_AUTH_HASH=${BASIC_AUTH_HASH}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./logs:/var/log/caddy
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - edge

volumes:
  caddy-data:
  caddy-config:

networks:
  edge:
    external: true
